.TH "models.transaction.Transaction" 3 "Wallet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
models.transaction.Transaction \- brief create a class Transaction in bd Base  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP = Column(Integer, primary_key=True, index=True)"
.br
.ti -1c
.RI "\fBcard_number\fP = Column(String)"
.br
.ti -1c
.RI "\fBtransaction_type\fP = Column(Enum(\fBTransactionStatus\fP))"
.br
.ti -1c
.RI "\fBtransaction_amount\fP = Column(Float)"
.br
.ti -1c
.RI "\fBtransaction_date_time\fP = Column(DateTime)"
.br
.ti -1c
.RI "\fBsender_recipient\fP = Column(String)"
.br
.in -1c
.SH "Detailed Description"
.PP 
brief create a class Transaction in bd Base 

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallet from the source code\&.
