.TH "models.base.Base" 3 "Wallet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
models.base.Base \- brief Base class for our models  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
brief Base class for our models 

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallet from the source code\&.
