.TH "models.transaction_selection.TransactionStatus" 3 "Wallet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
models.transaction_selection.TransactionStatus \- brief create a transaction type class that determines whether the transaction is a credit or debit transaction  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcrediting\fP = 1"
.br
.ti -1c
.RI "int \fBdebiting\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
brief create a transaction type class that determines whether the transaction is a credit or debit transaction 

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallet from the source code\&.
