.TH "services.database_context.DatabaseContext" 3 "Wallet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services.database_context.DatabaseContext \- brief create a class DatabaseContext  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdatabase_engine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
brief create a class DatabaseContext 

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallet from the source code\&.
