.TH "services.transaction_service.TransactionService" 3 "Wallet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services.transaction_service.TransactionService \- brief create a class TransactionService  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBadd_transaction\fP (self, transaction)"
.br
.ti -1c
.RI "\fBget_all_transactions\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
brief create a class TransactionService 

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallet from the source code\&.
