.TH "services.card_service.CardService" 3 "Wallet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services.card_service.CardService \- brief create a class CardService  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBadd_card\fP (self, card)"
.br
.ti -1c
.RI "\fBget_all_cards\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
brief create a class CardService 

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallet from the source code\&.
