name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Init dependencies
      run: make init

    - name: Build package
      run: make build

    - name: Run tests
      run: make test

    - name: Clear envinronment
      run: make clean

    # TODO:
    #- name: configure
    #  run: ./configure

    #- name: Install dependencies
    #  run: make

    #- name: Run check
    #  run: make check

    #- name: Run distcheck
    #  run: make distcheck
